version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka1:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3

  query:
    build: ./query
    container_name: query
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
      - kafka1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/hits
      - DATABASE_NAME=admin
      - DATABASE_PASSWORD=admin

  stats-db:
    image: postgres:15-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=hits
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  command:
    build: ./command
    container_name: command
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - kafka1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main
      - DATABASE_NAME=admin
      - DATABASE_PASSWORD=admin

  main-db:
    image: postgres:15-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin