spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: kafka-example-consumer
  kafka:
    topic:
      name: topic-demo
    # Адреса всех брокеров кластера
#    bootstrap-servers: localhost:9092
    bootstrap-servers: kafka1:9092
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${spring.application.name}
      autoOffsetReset: earliest
      key-Deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-Deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.value.default.type: consumer.core.entity.Post
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: java.util, java.lang, consumer.core.entity, consumer.core.entity.*, kafka.core.dto.PostDto, kafka.core.entity.Post



